[package]
name = "rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web= "4"
actix-files= "0.6.2"
futures-util="0.3.21"
maud="0.24.0"